project:
  type: website

website:
  title: "CS/DS 549 Lectures"
  back-to-top-navigation: true
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home
      - section: "*nux Shell and Shared Computing Cluster"
        contents:
          - command_shells.qmd
          - scc.qmd
      - section: "Git"
        contents:
          - lecture02.qmd
      - section: "VS Code"
        contents:
          - lecture03.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



