project:
  type: website
  output-dir: ../quarto-lectures-website  # _site
  render:
    - quarto-render-source/index.qmd
    - quarto-render-source/01_command_shells.qmd

execute: 
  freeze: auto

website:
  title: "CS/DS 549 Lectures and Assignments"
  back-to-top-navigation: true
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home
      - 01_command_shells.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: false



